version: '3.9'

services:
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: xurapass-postgres
    environment:
      POSTGRES_DB: xurapass
      POSTGRES_USER: xurapass_user
      POSTGRES_PASSWORD: xurapass_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xurapass_user -d xurapass"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  db-test:
    image: postgres:14.19-alpine3.21
    container_name: xurapass-postgres-test
    environment:
      POSTGRES_DB: xurapass_test
      POSTGRES_USER: xurapass_user
      POSTGRES_PASSWORD: xurapass_password
    ports:
      - "5433:5432"
    volumes:
      - ./src/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xurapass_user -d xurapass_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data: